"""Charges, checked against arithmetic done by hand rather than by the module.

Every expected number in this file is worked out longhand in the test's own
comments. That is the only way a cost model is worth anything: if the expected
values were generated by running the code, the tests would pin the behaviour
without ever having established that the behaviour is right.

The case that motivated the module is `test_costs_scale_with_size`. The old flat
model charged brokerage only, so its cost was identical at 1 lot and at 10 —
which flattered every strategy exactly as it was sized up into the range where
the flattery mattered.
"""

from datetime import date

import pytest

from app.backtest.costs import (
    SCHEDULES,
    Charges,
    CostModel,
    Fill,
    exercise_stt,
    rates_for,
)

LOT = 75

# Three dates, one in each rate regime.
PRE_2024 = date(2024, 9, 30)     # STT 0.0625%, exchange 0.05%
MID_2025 = date(2025, 6, 12)     # STT 0.10%,   exchange 0.03503%
NOW_2026 = date(2026, 8, 14)     # STT 0.15%,   exchange 0.03553%


# ---------------------------------------------------------------------------
# the schedule itself
# ---------------------------------------------------------------------------

def test_schedules_are_ordered_by_effective_date():
    """`rates_for` walks the list and breaks on the first future entry, so an
    out-of-order insert would silently return the wrong regime."""
    dates = [s.effective for s in SCHEDULES]
    assert dates == sorted(dates)


@pytest.mark.parametrize("day, stt", [
    (date(2021, 8, 16), 0.000625),   # lake's first day
    (date(2024, 9, 30), 0.000625),   # last day of the old regime
    (date(2024, 10, 1), 0.001),      # Budget 2024 takes effect
    (date(2026, 3, 31), 0.001),      # last day before Budget 2026
    (date(2026, 4, 1), 0.0015),      # Budget 2026 takes effect
    (date(2026, 8, 14), 0.0015),
])
def test_rates_for_resolves_the_regime_in_force(day, stt):
    assert rates_for(day).stt_sell_premium == stt


def test_dates_before_the_first_schedule_get_the_first_schedule():
    """Deliberate: a vendor with deeper history should not make the engine
    raise. Pricing 2019 slightly wrong beats refusing to price it."""
    assert rates_for(date(2015, 1, 1)) is SCHEDULES[0]


# ---------------------------------------------------------------------------
# a short straddle, worked longhand
# ---------------------------------------------------------------------------

def test_short_straddle_entry_matches_hand_calculation():
    """SELL 1 lot each of a 100-point CE and PE on 2026-08-14.

    Sell turnover = 100 x 75 x 2                       = 15,000
      brokerage   = 20 x 2 orders                      =     40
      STT         = 15,000 x 0.0015                    =     22.50
      exchange    = 15,000 x 0.0003553                 =      5.3295
      SEBI        = 15,000 x 0.000001                  =      0.015
      stamp       = nothing bought                     =      0
      GST         = (40 + 5.3295 + 0.015) x 0.18       =      8.16201
                                                        ----------
                                                          76.00651
    """
    fills = [Fill("SELL", 100.0, LOT), Fill("SELL", 100.0, LOT)]
    charges = CostModel().charge(fills, NOW_2026)

    assert charges.brokerage == pytest.approx(40.0)
    assert charges.stt == pytest.approx(22.50)
    assert charges.exchange == pytest.approx(5.3295)
    assert charges.sebi == pytest.approx(0.015)
    assert charges.stamp == pytest.approx(0.0)
    assert charges.gst == pytest.approx(8.16201)
    assert charges.total == pytest.approx(76.00651)


def test_short_straddle_exit_matches_hand_calculation():
    """Buying the same straddle back at 60 points each.

    Buy turnover  = 60 x 75 x 2                        =  9,000
      brokerage   = 20 x 2                             =     40
      STT         = nothing sold                       =      0
      exchange    = 9,000 x 0.0003553                  =      3.1977
      SEBI        = 9,000 x 0.000001                   =      0.009
      stamp       = 9,000 x 0.00003                    =      0.27
      GST         = (40 + 3.1977 + 0.009) x 0.18       =      7.777206
                                                        ----------
                                                          51.253906
    """
    fills = [Fill("BUY", 60.0, LOT), Fill("BUY", 60.0, LOT)]
    charges = CostModel().charge(fills, NOW_2026)

    assert charges.stt == pytest.approx(0.0)
    assert charges.stamp == pytest.approx(0.27)
    assert charges.total == pytest.approx(51.253906)


def test_round_trip_is_the_sum_of_both_sides():
    entry = [Fill("SELL", 100.0, LOT), Fill("SELL", 100.0, LOT)]
    exit_ = [Fill("BUY", 60.0, LOT), Fill("BUY", 60.0, LOT)]

    total = CostModel().round_trip(entry, exit_, NOW_2026)

    # 76.00651 + 51.253906
    assert total.total == pytest.approx(127.260416)
    # The old flat model charged 20 x 2 legs x 2 sides = 80 for this trade.
    assert total.total > 80.0


# ---------------------------------------------------------------------------
# the property the flat model got wrong
# ---------------------------------------------------------------------------

def test_costs_scale_with_size():
    """Ten lots is not ten times one lot — brokerage is flat, the rest scales.

    This is the whole reason the module exists. The old model returned 80 for
    both of these.
    """
    def straddle(lots: int) -> Charges:
        quantity = lots * LOT
        return CostModel().round_trip(
            [Fill("SELL", 100.0, quantity), Fill("SELL", 100.0, quantity)],
            [Fill("BUY", 60.0, quantity), Fill("BUY", 60.0, quantity)],
            NOW_2026,
        )

    one, ten = straddle(1), straddle(10)

    # Brokerage is per order, so it does not move at all.
    assert ten.brokerage == pytest.approx(one.brokerage)
    # STT is purely proportional, so it moves exactly ten-fold.
    assert ten.stt == pytest.approx(one.stt * 10)
    # The total lands above 400 against the flat model's unchanging 80.
    assert ten.total == pytest.approx(423.00416)


def test_charges_add_componentwise():
    a = Charges(brokerage=40.0, stt=22.5, gst=8.0)
    b = Charges(brokerage=40.0, stamp=0.27, gst=7.5)
    combined = a + b

    assert combined.brokerage == pytest.approx(80.0)
    assert combined.stt == pytest.approx(22.5)
    assert combined.stamp == pytest.approx(0.27)
    assert combined.gst == pytest.approx(15.5)


def test_charges_sum_from_empty_start():
    """`sum(charges, Charges())` is how the engine totals a run's trades."""
    items = [Charges(stt=1.0), Charges(stt=2.0), Charges(stt=4.0)]
    assert sum(items, Charges()).stt == pytest.approx(7.0)


# ---------------------------------------------------------------------------
# which charge falls on which side
# ---------------------------------------------------------------------------

def test_stt_falls_only_on_the_sell_side():
    model = CostModel()
    sold = model.charge([Fill("SELL", 100.0, LOT)], NOW_2026)
    bought = model.charge([Fill("BUY", 100.0, LOT)], NOW_2026)

    assert sold.stt > 0
    assert bought.stt == pytest.approx(0.0)


def test_stamp_duty_falls_only_on_the_buy_side():
    model = CostModel()
    sold = model.charge([Fill("SELL", 100.0, LOT)], NOW_2026)
    bought = model.charge([Fill("BUY", 100.0, LOT)], NOW_2026)

    assert sold.stamp == pytest.approx(0.0)
    assert bought.stamp > 0


def test_exchange_and_sebi_fall_on_both_sides():
    model = CostModel()
    sold = model.charge([Fill("SELL", 100.0, LOT)], NOW_2026)
    bought = model.charge([Fill("BUY", 100.0, LOT)], NOW_2026)

    assert sold.exchange == pytest.approx(bought.exchange)
    assert sold.sebi == pytest.approx(bought.sebi)


def test_gst_excludes_stt_and_stamp_duty():
    """GST is on brokerage + exchange + SEBI only. Charging it on STT would
    inflate a seller's costs by roughly 18% of the largest line."""
    charges = CostModel().charge([Fill("SELL", 100.0, LOT)], NOW_2026)
    expected = (charges.brokerage + charges.exchange + charges.sebi) * 0.18

    assert charges.gst == pytest.approx(expected)
    assert charges.gst < charges.stt * 0.18 + expected


def test_a_credit_basket_still_pays_stamp_duty_on_its_long_leg():
    """A short strangle with a protective wing nets to a credit, but the wing
    was bought, and stamp duty does not care about the net."""
    charges = CostModel().charge(
        [Fill("SELL", 100.0, LOT), Fill("BUY", 20.0, LOT)], NOW_2026)

    assert charges.stamp == pytest.approx(20.0 * LOT * 0.00003)
    assert charges.stt == pytest.approx(100.0 * LOT * 0.0015)


# ---------------------------------------------------------------------------
# rate changes inside the lake's range
# ---------------------------------------------------------------------------

def test_the_same_trade_costs_different_amounts_in_different_regimes():
    """A backtest spanning 2021-2026 crosses two rate changes. Pricing every
    trade at today's rates would overstate the cost of the older half."""
    fills = [Fill("SELL", 100.0, LOT), Fill("SELL", 100.0, LOT)]
    model = CostModel()

    old = model.charge(fills, PRE_2024)
    mid = model.charge(fills, MID_2025)
    new = model.charge(fills, NOW_2026)

    assert old.stt < mid.stt < new.stt
    # 15,000 x 0.000625 = 9.375
    assert old.stt == pytest.approx(9.375)
    # 15,000 x 0.001 = 15.0
    assert mid.stt == pytest.approx(15.0)
    # 15,000 x 0.0015 = 22.5
    assert new.stt == pytest.approx(22.5)


def test_exchange_charge_fell_when_stt_rose_in_october_2024():
    """The two October 2024 changes pushed in opposite directions — SEBI's
    uniform charge cut the exchange fee from 0.05% to 0.03503% in the same week
    STT went up. A model with only one of them gets the sign of the change
    wrong."""
    fills = [Fill("SELL", 100.0, LOT)]
    model = CostModel()

    assert model.charge(fills, PRE_2024).exchange > \
        model.charge(fills, MID_2025).exchange


# ---------------------------------------------------------------------------
# the expiry trap
# ---------------------------------------------------------------------------

def test_exercise_stt_is_charged_on_intrinsic_not_premium():
    """A 200-point ITM call on one lot: 200 x 75 x 0.0015 = 22.50, regardless
    of the premium paid for it."""
    assert exercise_stt(200.0, LOT, NOW_2026) == pytest.approx(22.50)


def _square_off_vs_expire(day: date) -> tuple[float, float]:
    """STT on the two ways out of a deep ITM long call.

    200 points of intrinsic, 202 of premium — two points of time value, which
    is realistic for a deep ITM contract near expiry.
    """
    square_off = CostModel().charge([Fill("SELL", 202.0, LOT)], day).stt
    expire = exercise_stt(200.0, LOT, day)
    return square_off, expire


def test_letting_it_expire_used_to_cost_twice_as_much():
    """The trap, in the regime where it was real. Before October 2024 the
    exercise rate was 0.125% against 0.0625% on premium — double. A backtest
    over the older half of the lake that ignores this overstates the profit of
    anything that held to expiry."""
    square_off, expire = _square_off_vs_expire(PRE_2024)

    assert expire == pytest.approx(18.75)
    assert square_off == pytest.approx(9.46875)
    assert expire / square_off == pytest.approx(1.98, abs=0.01)


def test_budget_2026_all_but_closed_the_gap():
    """Both rates are now 0.15%, so expiry is fractionally *cheaper* than
    squaring off — intrinsic is smaller than premium by the time value, and
    there is no exit brokerage.

    Recorded because the conventional advice ("never let it expire ITM")
    inverted inside our own sample, and a strategy built today should not be
    contorted to avoid a cost that no longer exists.
    """
    square_off, expire = _square_off_vs_expire(NOW_2026)

    assert expire < square_off
    assert expire / square_off == pytest.approx(0.99, abs=0.01)


def test_exercise_stt_is_zero_out_of_the_money():
    assert exercise_stt(0.0, LOT, NOW_2026) == 0.0
    assert exercise_stt(-50.0, LOT, NOW_2026) == 0.0


def test_exercise_stt_uses_the_rate_in_force():
    # 0.125% before April 2026, 0.15% after.
    assert exercise_stt(200.0, LOT, MID_2025) == pytest.approx(18.75)
    assert exercise_stt(200.0, LOT, NOW_2026) == pytest.approx(22.50)


# ---------------------------------------------------------------------------
# configuration
# ---------------------------------------------------------------------------

def test_brokerage_can_be_switched_off_to_isolate_statutory_cost():
    """"Is the edge bigger than the tax" is a different question from "is it
    bigger than the tax plus this particular broker"."""
    fills = [Fill("SELL", 100.0, LOT)]
    statutory = CostModel(charge_brokerage=False).charge(fills, NOW_2026)

    assert statutory.brokerage == 0.0
    assert statutory.stt > 0
    # GST follows brokerage down, since it is levied on it.
    assert statutory.gst == pytest.approx(
        (statutory.exchange + statutory.sebi) * 0.18)


def test_no_fills_costs_nothing():
    assert CostModel().charge([], NOW_2026).total == 0.0
